/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CisaRouteImport } from './routes/cisa'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CisaRoute = CisaRouteImport.update({
  id: '/cisa',
  path: '/cisa',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cisa': typeof CisaRoute
  '/history': typeof HistoryRoute
  '/mitre': typeof MitreRoute
  '/playbooks': typeof PlaybooksRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cisa': typeof CisaRoute
  '/history': typeof HistoryRoute
  '/mitre': typeof MitreRoute
  '/playbooks': typeof PlaybooksRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cisa': typeof CisaRoute
  '/history': typeof HistoryRoute
  '/mitre': typeof MitreRoute
  '/playbooks': typeof PlaybooksRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cisa'
    | '/history'
    | '/mitre'
    | '/playbooks'
    | '/reports'
    | '/settings'
    | '/threat-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cisa'
    | '/history'
    | '/mitre'
    | '/playbooks'
    | '/reports'
    | '/settings'
    | '/threat-intelligence'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cisa'
    | '/history'
    | '/mitre'
    | '/playbooks'
    | '/reports'
    | '/settings'
    | '/threat-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CisaRoute: typeof CisaRoute
  HistoryRoute: typeof HistoryRoute
  MitreRoute: typeof MitreRoute
  PlaybooksRoute: typeof PlaybooksRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cisa': {
      id: '/cisa'
      path: '/cisa'
      fullPath: '/cisa'
      preLoaderRoute: typeof CisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CisaRoute: CisaRoute,
  HistoryRoute: HistoryRoute,
  MitreRoute: MitreRoute,
  PlaybooksRoute: PlaybooksRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
